name: CommCare Core Build

on:
  push:
    branches:
      - 'master'
      - 'formplayer'
  pull_request:
    branches:
      - 'master'
      - 'formplayer'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: '17'
      JOB_GRADLE_VERSION: 7.3
      FORMPLAYER_GRADLE_VERSION: 7.3
      FORMPLAYER_JAVA_VERSION: '17'
    steps:
      - uses: actions/checkout@v3
      - name: Set environment for Formplayer
        if: ${{ github.ref_name == 'formplayer' || github.base_ref == 'formplayer' }}
        run: |
          echo "JOB_GRADLE_VERSION=${{ env.FORMPLAYER_GRADLE_VERSION }}" >> "$GITHUB_ENV"
          echo "JAVA_VERSION=${{ env.FORMPLAYER_JAVA_VERSION }}" >> "$GITHUB_ENV"
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'adopt'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ env.JOB_GRADLE_VERSION }}
          arguments: build
